### ISSUE TITLE
upgrade to Kamon 1.0

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/kamon-spm#13]
Hello people! (specially @otisg)

This module should be upgraded for Kamon 1.0, can anyone give a hand with that? Thanks :)

**Comment by qkoshelev** [comment]
Hello @ivantopo 
I have started working on it.

**Comment by otisg** [comment]
#14 is the PR if you want to review/merge, @ivantopo

**Comment by otisg** [comment]
This be closed now, @dpsoft ?

**Comment by dpsoft** [comment]
closed with https://github.com/kamon-io/kamon-spm/pull/14
