### ISSUE TITLE
replace spray-client with alternate http client

### ISSUE THREAD

**Issue by pjfanning** [kamon-io/kamon-spm#3]
Moving issue from https://github.com/kamon-io/Kamon/issues/427.
My key concern is that spray is no longer (except for maybe, spray-json) and that the continued use of spray-client will prevent the creation of a scala 2.12 compatible kamon-spm jar.
I have some of the work done for switching to akka-http client (https://github.com/pjfanning/kamon-spm/tree/akka-http-client).
I suspect that this will enforce a dependency on akka 2.4.x that will make it awkward for users of kamon-spray or kamon-akka users who still use akka 2.3.x.
I wonder if it would be better to use a neutral http client like Apache HttpAyncClient.

**Comment by dpsoft** [comment]
@pjfanning here a PR for `kamon-influx` using `AsyncHTTPClient` https://github.com/kamon-io/kamon-influxdb/pull/2

**Comment by dpsoft** [comment]
@qkoshelev @otisg ping!!!

**Comment by pjfanning** [comment]
I have a partial implementation using asynchttpclient at https://github.com/pjfanning/kamon-spm/commit/3fee1ca479edac58ce1538419ed5089f04d28906

**Comment by pjfanning** [comment]
I have a version of the code published at https://jitpack.io/#pjfanning/kamon-spm/v0.6.5-alpha1

**Comment by otisg** [comment]
I had a quick look at the original issue + the diff.  LGTM

**Comment by qkoshelev** [comment]
Looks good to me as well.

**Comment by otisg** [comment]
Merge away, please :)

**Comment by dpsoft** [comment]
done with https://github.com/kamon-io/kamon-spm/pull/4
