### ISSUE TITLE
Add support for sending data to SPM via proxy

### ISSUE THREAD

**Issue by otisg** [kamon-io/kamon-spm#8]

**Comment by otisg** [comment]
@ivantopo @dpsoft is there a particular pattern we should follow here, that other backends are either using or should be using for proxy support?  Or maybe there is already some code/functionality we should be (re)using for this?

**Comment by synox** [comment]
from the user point of view, using the java standards https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html would be the easiest.

**Comment by synox** [comment]
See PR https://github.com/kamon-io/kamon-spm/pull/9

**Comment by dpsoft** [comment]
closed via https://github.com/kamon-io/kamon-spm/pull/9
